### ISSUE TITLE
Why publish an empty package?

### ISSUE THREAD

**Issue by thosakwe** [sql-dart/mysql#1]
Squatted names were such a problem on NPM, that NPM had to introduce scoped packages.

Why publish a package with the name `mysql` if there is no code?

People will search for a MySQL driver on Pub, be disappointed that there’s no functionality, and continue to write off Dart as a server-side platform.

So please, for the good of the Dart ecosystem, please don’t publish empty packages again.

**Comment by vanesyan** [comment]
Hello there, I've been writing around code locally for awhile, so it will be available soon on dart pub as well as in this repo. You're right about package placeholder, may be it was a not so good idea, but I really like "mysql" package name for the project, so the project description currently explicit about that the package is just a placeholder for now.

**Comment by thosakwe** [comment]
Okay, well, just for the future, know that you can publish incomplete code to Pub - just put a “0.0.x” version on it, and it’ll be clear that it’s in active development.

**Comment by renblau** [comment]
Any updates?

**Comment by renblau** [comment]
Okay, thanks.
Just out of curiosity: How is it going to differ from sqljocky5?

**Comment by vanesyan** [comment]
Cannot compare with sqljocky5, I don't really no its internals.

But I can describe this driver features briefly.

This driver relies on `sql` package, which is currently also in development. The `sql` package defines common interfaces to be implemented by drivers, while also providing generic database structures like pool, self managed connections, connection helper functions, etc., so you can think about it as analog of `sql` in Go, but for Dart. 

The `sql` aims to solve 2 main problems:
1) Defines common interface for SQL-like database drivers, so canonize the way how to interact with various SQL database, which also leads to relatively easy migration from one database to another, while using 99% the same code in Dart.
2) Frees developers of SQL drivers to reimplement connection manager, pool, etc. and allows to focus on primary target - database driver development.

This mysql driver implements all those interfaces from `sql`. Beside this, this driver implementation has good separation of protocol specific code, from user-end interfaces.

This package also provides completely static-typed code (which by default make it compatible with Dart 2) and uses as little runtime type checking as possible.
